name: TIG-test1
favicon: null
layout_spectrum: 0.38839
typography_spectrum: 0.6670969331171364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2eab1f'
    - '#ff7d3f'
    - '#ffffff'
    - '#bee4b9'
    - '#ffbc9c'
  brandStrength: 0.7728123411070555
  lightness: 0.9818921179976314
  saturation: 0.6499564808327705
  rhythmicContrast: 0.8347397446632385
purpose: []
