name: TIG-test1
favicon: null
layout_spectrum: 0.38839
typography_spectrum: 0.6670969331171364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7728123411070555
  lightness: 0.9818921179976314
  saturation: 0.6499564808327705
  rhythmicContrast: 0.8347397446632385
purpose: []
